// Package render emits a resolved theme as JSON (for nix), Lua (for the nvim
// colorscheme plugin), or a human-readable ANSI preview.
package render

import (
	"encoding/json"
	"fmt"
	"io"
	"slices"

	"github.com/0xcharly/nix-config/splicedpixel/internal/theme"
)

type jsonToken struct {
	Hex string `json:"hex"`
	RGB [3]int `json:"rgb"`
}

type jsonTheme struct {
	Name   string               `json:"name"`
	Tokens map[string]jsonToken `json:"tokens"`
}

// JSON writes the resolved theme as sorted, indented JSON.
func JSON(w io.Writer, res *theme.Resolved) error {
	out := jsonTheme{Name: res.Name, Tokens: make(map[string]jsonToken, len(res.Tokens))}
	for name, c := range res.Tokens {
		r, g, b := c.SRGB()
		out.Tokens[name] = jsonToken{Hex: c.Hex(), RGB: [3]int{int(r), int(g), int(b)}}
	}
	data, err := json.MarshalIndent(out, "", "  ")
	if err != nil {
		return err
	}
	_, err = fmt.Fprintf(w, "%s\n", data)
	return err
}

// Lua writes the resolved theme as a Lua module returning a table of
// token -> 24-bit integer, sorted alphabetically.
func Lua(w io.Writer, res *theme.Resolved) error {
	if _, err := fmt.Fprintf(w, "-- Generated by splicedpixel. Do not edit.\nreturn {\n"); err != nil {
		return err
	}
	names := make([]string, 0, len(res.Tokens))
	for name := range res.Tokens {
		names = append(names, name)
	}
	slices.Sort(names)
	for _, name := range names {
		if _, err := fmt.Fprintf(w, "  %s = 0x%s,\n", name, res.Tokens[name].Hex()); err != nil {
			return err
		}
	}
	_, err := fmt.Fprintf(w, "}\n")
	return err
}
