keys:
  - &user_delay age13j49fp8pdgqgz72q3gjhh7xshawj5cuy84q77p2c66e944w4kvgs906qhs
  - &home_nyx age1lpwsnmj0dvyhz6negh77yh3cnrwfu6xurfdlr7v8e966uspeqsasq6ycqu
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *user_delay
      - *home_nyx
