[package]
name = "find-git-repositories"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.20", features = ["derive"] }
rmp-serde = "1.3.0"
rust-analyzer = "0.0.1"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
