[package]
name = "zellij-switch-session"
version = "0.1.0"
edition = "2021"

[features]
default = ["zellij_run_command_api"]
zellij_fallback_fs_api = []
zellij_run_command_api = []

[dependencies]
ansi_term = "0.12.1"
anyhow = "1.0"
bstr = "1.10.0"
data-encoding = "2.6.0"
fuzzy-matcher = "0.3.7"
itertools = "0.13.0"
rmp-serde = "1.3.0"
rust-analyzer = "0.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.10.6"
sha2 = "0.10.8"
thiserror = "1.0"
zellij-tile = "0.40.1"

# [dependencies.find-git-repositories]
# path = "find-git-repositories"

[workspace]
members = ["find-git-repositories"]
