[tool.poetry]
name = "sekrets"
version = "0.1.0"
description = "Utility script to manipulate personal vault and stored secrets."
authors = ["Charly Delay <charly@delay.gg>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12.0"
bcrypt = "^4.2.0"
cryptography = ">=43.0.0"
rich = ">=13.7.0"
typing-extensions = { version = ">=4.0.0, <5.0", python = "<3.9" }

# [tool.poetry.dev-dependencies]
# pytest = "^7.0.0"
# black = "^22.6"
# pytest-cov = "^3.0.0"
# attrs = "^21.4.0"
# pre-commit = "^2.17.0"

[tool.poetry.scripts]
sekrets = "sekrets:_main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
